# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'browse.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 518)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 1011, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(440, 100, 141, 20))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.dest_btn = QtWidgets.QPushButton(self.frame)
        self.dest_btn.setGeometry(QtCore.QRect(300, 120, 91, 21))
        self.dest_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dest_btn.setStyleSheet("")
        self.dest_btn.setObjectName("dest_btn")
        self.source_txt = QtWidgets.QLineEdit(self.frame)
        self.source_txt.setEnabled(False)
        self.source_txt.setGeometry(QtCore.QRect(10, 40, 281, 21))
        self.source_txt.setStyleSheet("")
        self.source_txt.setObjectName("source_txt")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 221, 16))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.source_btn = QtWidgets.QPushButton(self.frame)
        self.source_btn.setGeometry(QtCore.QRect(300, 40, 91, 21))
        self.source_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.source_btn.setMouseTracking(True)
        self.source_btn.setStyleSheet("")
        self.source_btn.setObjectName("source_btn")
        self.dest_txt = QtWidgets.QLineEdit(self.frame)
        self.dest_txt.setEnabled(False)
        self.dest_txt.setGeometry(QtCore.QRect(10, 120, 281, 21))
        self.dest_txt.setStyleSheet("")
        self.dest_txt.setObjectName("dest_txt")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 231, 16))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.check_btn_2 = QtWidgets.QPushButton(self.frame)
        self.check_btn_2.setEnabled(False)
        self.check_btn_2.setGeometry(QtCore.QRect(300, 150, 91, 21))
        self.check_btn_2.setObjectName("check_btn_2")
        self.macro_name = QtWidgets.QLineEdit(self.frame)
        self.macro_name.setEnabled(False)
        self.macro_name.setGeometry(QtCore.QRect(440, 40, 291, 21))
        self.macro_name.setObjectName("macro_name")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(440, 20, 91, 16))
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(770, 30, 201, 41))
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setDigitCount(11)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Hex)
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(520, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pb = QtWidgets.QProgressBar(self.frame)
        self.pb.setGeometry(QtCore.QRect(440, 120, 301, 21))
        self.pb.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.pb.setProperty("value", 24)
        self.pb.setOrientation(QtCore.Qt.Horizontal)
        self.pb.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pb.setObjectName("pb")
        self.check_btn_1 = QtWidgets.QPushButton(self.frame)
        self.check_btn_1.setEnabled(False)
        self.check_btn_1.setGeometry(QtCore.QRect(300, 70, 91, 21))
        self.check_btn_1.setObjectName("check_btn_1")
        self.ok_btn = QtWidgets.QPushButton(self.frame)
        self.ok_btn.setEnabled(False)
        self.ok_btn.setGeometry(QtCore.QRect(440, 150, 111, 21))
        self.ok_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_btn.setStyleSheet("")
        self.ok_btn.setObjectName("ok_btn")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(690, 20, 41, 17))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setStyleSheet("")
        self.checkBox.setObjectName("checkBox")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(849, 160, 161, 80))
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(20, 10, 21, 21))
        self.radioButton.setAutoFillBackground(True)
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 250, 1011, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_7.setEnabled(True)
        self.checkBox_7.setGeometry(QtCore.QRect(800, 140, 121, 17))
        self.checkBox_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setGeometry(QtCore.QRect(800, 40, 121, 17))
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setGeometry(QtCore.QRect(800, 60, 121, 17))
        self.checkBox_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_8.setEnabled(True)
        self.checkBox_8.setGeometry(QtCore.QRect(800, 160, 121, 17))
        self.checkBox_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_9.setGeometry(QtCore.QRect(800, 20, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(440, 20, 91, 16))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.source_btn_2 = QtWidgets.QPushButton(self.frame_2)
        self.source_btn_2.setGeometry(QtCore.QRect(300, 40, 91, 21))
        self.source_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.source_btn_2.setMouseTracking(True)
        self.source_btn_2.setStyleSheet("")
        self.source_btn_2.setObjectName("source_btn_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setGeometry(QtCore.QRect(800, 80, 121, 17))
        self.checkBox_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_6.setEnabled(True)
        self.checkBox_6.setGeometry(QtCore.QRect(800, 120, 121, 17))
        self.checkBox_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_5.setEnabled(True)
        self.checkBox_5.setGeometry(QtCore.QRect(800, 100, 121, 17))
        self.checkBox_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 221, 16))
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.check_btn_4 = QtWidgets.QPushButton(self.frame_2)
        self.check_btn_4.setEnabled(False)
        self.check_btn_4.setGeometry(QtCore.QRect(300, 150, 91, 21))
        self.check_btn_4.setObjectName("check_btn_4")
        self.ok_btn_2 = QtWidgets.QPushButton(self.frame_2)
        self.ok_btn_2.setEnabled(False)
        self.ok_btn_2.setGeometry(QtCore.QRect(440, 160, 111, 21))
        self.ok_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_btn_2.setStyleSheet("")
        self.ok_btn_2.setObjectName("ok_btn_2")
        self.dest_btn_2 = QtWidgets.QPushButton(self.frame_2)
        self.dest_btn_2.setGeometry(QtCore.QRect(300, 120, 91, 21))
        self.dest_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dest_btn_2.setStyleSheet("")
        self.dest_btn_2.setObjectName("dest_btn_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setEnabled(False)
        self.label_10.setGeometry(QtCore.QRect(520, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pb_2 = QtWidgets.QProgressBar(self.frame_2)
        self.pb_2.setGeometry(QtCore.QRect(440, 130, 301, 21))
        self.pb_2.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.pb_2.setProperty("value", 0)
        self.pb_2.setOrientation(QtCore.Qt.Horizontal)
        self.pb_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.pb_2.setObjectName("pb_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 231, 16))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(440, 110, 141, 20))
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.source_txt_2 = QtWidgets.QLineEdit(self.frame_2)
        self.source_txt_2.setEnabled(False)
        self.source_txt_2.setGeometry(QtCore.QRect(10, 40, 281, 21))
        self.source_txt_2.setStyleSheet("")
        self.source_txt_2.setObjectName("source_txt_2")
        self.macro_name_2 = QtWidgets.QLineEdit(self.frame_2)
        self.macro_name_2.setEnabled(False)
        self.macro_name_2.setGeometry(QtCore.QRect(440, 40, 291, 21))
        self.macro_name_2.setObjectName("macro_name_2")
        self.check_btn_3 = QtWidgets.QPushButton(self.frame_2)
        self.check_btn_3.setEnabled(False)
        self.check_btn_3.setGeometry(QtCore.QRect(300, 70, 91, 21))
        self.check_btn_3.setObjectName("check_btn_3")
        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_10.setGeometry(QtCore.QRect(690, 20, 41, 17))
        self.checkBox_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_10.setStyleSheet("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.dest_txt_2 = QtWidgets.QLineEdit(self.frame_2)
        self.dest_txt_2.setEnabled(False)
        self.dest_txt_2.setGeometry(QtCore.QRect(10, 120, 281, 21))
        self.dest_txt_2.setStyleSheet("")
        self.dest_txt_2.setObjectName("dest_txt_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 230, 21, 41))
        self.radioButton_2.setAutoFillBackground(True)
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 240, 61, 21))
        self.label_12.setAutoFillBackground(True)
        self.label_12.setObjectName("label_12")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 71, 21))
        self.label_3.setAutoFillBackground(True)
        self.label_3.setObjectName("label_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(860, 180, 161, 81))
        self.frame_4.setAutoFillBackground(True)
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.reset_btn = QtWidgets.QPushButton(self.frame_4)
        self.reset_btn.setEnabled(False)
        self.reset_btn.setGeometry(QtCore.QRect(30, 40, 91, 31))
        self.reset_btn.setStyleSheet("")
        self.reset_btn.setObjectName("reset_btn")
        self.reset_lbl = QtWidgets.QLabel(self.frame_4)
        self.reset_lbl.setEnabled(False)
        self.reset_lbl.setGeometry(QtCore.QRect(30, 10, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.reset_lbl.setFont(font)
        self.reset_lbl.setStyleSheet("font: 75 10pt \"Leelawadee UI\";")
        self.reset_lbl.setObjectName("reset_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Applying macro:"))
        self.dest_btn.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Source Excel_file(.xlsm):"))
        self.source_btn.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Destination of Excel_file(.xlsx):"))
        self.check_btn_2.setText(_translate("MainWindow", "Check Excel"))
        self.label_6.setText(_translate("MainWindow", "Macro name:"))
        self.label_9.setText(_translate("MainWindow", "(ex: Module1.Macro1)"))
        self.check_btn_1.setText(_translate("MainWindow", "Check Excel"))
        self.ok_btn.setText(_translate("MainWindow", "Apply_Macro"))
        self.checkBox.setText(_translate("MainWindow", "Edit"))
        self.checkBox_9.setText(_translate("MainWindow", "All"))
        self.label_8.setText(_translate("MainWindow", "Macro name:"))
        self.source_btn_2.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "Source Excel_file(.xlsm):"))
        self.check_btn_4.setText(_translate("MainWindow", "Check Excel"))
        self.ok_btn_2.setText(_translate("MainWindow", "Apply_Macro"))
        self.dest_btn_2.setText(_translate("MainWindow", "Browse"))
        self.label_10.setText(_translate("MainWindow", "(ex: Module1.Macro1)"))
        self.label_4.setText(_translate("MainWindow", "Destination of Excel_file(.xlsx):"))
        self.label_11.setText(_translate("MainWindow", "Applying macro:"))
        self.macro_name_2.setText(_translate("MainWindow", "Module2.Macro1"))
        self.check_btn_3.setText(_translate("MainWindow", "Check Excel"))
        self.checkBox_10.setText(_translate("MainWindow", "Edit"))
        self.label_12.setText(_translate("MainWindow", "Multi Sheet"))
        self.label_3.setText(_translate("MainWindow", " Single Sheet"))
        self.reset_btn.setText(_translate("MainWindow", "Reset"))
        self.reset_lbl.setText(_translate("MainWindow", "    For Reset:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

