# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sheet.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sheet_Dialog(object):
    def setupUi(self, Sheet_Dialog):
        Sheet_Dialog.setObjectName("Sheet_Dialog")
        Sheet_Dialog.resize(363, 197)
        Sheet_Dialog.setStyleSheet("")
        self.buttonBox = QtWidgets.QDialogButtonBox(Sheet_Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(80, 140, 181, 32))
        self.buttonBox.setStyleSheet("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(Sheet_Dialog)
        self.comboBox.setGeometry(QtCore.QRect(100, 70, 171, 31))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(Sheet_Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 40, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Sheet_Dialog)
        self.buttonBox.accepted.connect(Sheet_Dialog.accept)
        self.buttonBox.rejected.connect(Sheet_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Sheet_Dialog)

    def retranslateUi(self, Sheet_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Sheet_Dialog.setWindowTitle(_translate("Sheet_Dialog", "Sheets"))
        self.label_3.setText(_translate("Sheet_Dialog", "Choose the sheet name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sheet_Dialog = QtWidgets.QDialog()
    ui = Ui_Sheet_Dialog()
    ui.setupUi(Sheet_Dialog)
    Sheet_Dialog.show()
    sys.exit(app.exec_())
