# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Done2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_done(object):
    def setupUi(self, Dialog_done):
        Dialog_done.setObjectName("Dialog_done")
        Dialog_done.resize(462, 116)
        self.label_2 = QtWidgets.QLabel(Dialog_done)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.close_btn4 = QtWidgets.QPushButton(Dialog_done)
        self.close_btn4.setGeometry(QtCore.QRect(360, 80, 75, 23))
        self.close_btn4.setObjectName("close_btn4")
        self.label = QtWidgets.QLabel(Dialog_done)
        self.label.setGeometry(QtCore.QRect(20, 10, 58, 23))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_done)
        QtCore.QMetaObject.connectSlotsByName(Dialog_done)

    def retranslateUi(self, Dialog_done):
        _translate = QtCore.QCoreApplication.translate
        Dialog_done.setWindowTitle(_translate("Dialog_done", "Complete"))
        self.label_2.setText(_translate("Dialog_done", "Exporting Data has been successfully complete"))
        self.close_btn4.setText(_translate("Dialog_done", "Ok"))
        self.label.setText(_translate("Dialog_done", "Done!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_done = QtWidgets.QDialog()
    ui = Ui_Dialog_done()
    ui.setupUi(Dialog_done)
    Dialog_done.show()
    sys.exit(app.exec_())
