# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error_path.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error_path(object):
    def setupUi(self, Error_path):
        Error_path.setObjectName("Error_path")
        Error_path.resize(473, 145)
        self.close_btn5 = QtWidgets.QPushButton(Error_path)
        self.close_btn5.setGeometry(QtCore.QRect(180, 110, 75, 23))
        self.close_btn5.setObjectName("close_btn5")
        self.label = QtWidgets.QLabel(Error_path)
        self.label.setGeometry(QtCore.QRect(40, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Error_path)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Error_path)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 411, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Error_path)
        QtCore.QMetaObject.connectSlotsByName(Error_path)

    def retranslateUi(self, Error_path):
        _translate = QtCore.QCoreApplication.translate
        Error_path.setWindowTitle(_translate("Error_path", "Error"))
        self.close_btn5.setText(_translate("Error_path", "Close"))
        self.label.setText(_translate("Error_path", "Warning:"))
        self.label_2.setText(_translate("Error_path", "Error during processing"))
        self.label_3.setText(_translate("Error_path", "Please check Error file in the directory of application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Error_path = QtWidgets.QDialog()
    ui = Ui_Error_path()
    ui.setupUi(Error_path)
    Error_path.show()
    sys.exit(app.exec_())
