# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error2(object):
    def setupUi(self, Error2):
        Error2.setObjectName("Error2")
        Error2.resize(405, 117)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Error2.sizePolicy().hasHeightForWidth())
        Error2.setSizePolicy(sizePolicy)
        self.close_btn2 = QtWidgets.QPushButton(Error2)
        self.close_btn2.setGeometry(QtCore.QRect(300, 80, 81, 23))
        self.close_btn2.setObjectName("close_btn2")
        self.layoutWidget = QtWidgets.QWidget(Error2)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 346, 49))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(Error2)
        QtCore.QMetaObject.connectSlotsByName(Error2)

    def retranslateUi(self, Error2):
        _translate = QtCore.QCoreApplication.translate
        Error2.setWindowTitle(_translate("Error2", "Data"))
        self.close_btn2.setText(_translate("Error2", "Close"))
        self.label.setText(_translate("Error2", "Data Exists"))
        self.label_2.setText(_translate("Error2", "You have already enter this sheet in DataBase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Error2 = QtWidgets.QDialog()
    ui = Ui_Error2()
    ui.setupUi(Error2)
    Error2.show()
    sys.exit(app.exec_())
