# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_list(object):
    def setupUi(self, list):
        list.setObjectName("list")
        list.resize(361, 476)
        self.listWidget = QtWidgets.QListWidget(list)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 341, 421))
        self.listWidget.setObjectName("listWidget")
        self.btn_dlt = QtWidgets.QPushButton(list)
        self.btn_dlt.setGeometry(QtCore.QRect(140, 440, 81, 23))
        self.btn_dlt.setObjectName("btn_dlt")

        self.retranslateUi(list)
        QtCore.QMetaObject.connectSlotsByName(list)

    def retranslateUi(self, list):
        _translate = QtCore.QCoreApplication.translate
        list.setWindowTitle(_translate("list", "SQL Sheets"))
        self.listWidget.setSortingEnabled(True)
        self.btn_dlt.setText(_translate("list", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    list = QtWidgets.QDialog()
    ui = Ui_list()
    ui.setupUi(list)
    list.show()
    sys.exit(app.exec_())
